# Generated by Django 2.1.7 on 2019-03-01 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190301_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDay', models.CharField(db_index=True, max_length=200, verbose_name='Название урока')),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(verbose_name='Описание Урока')),
                ('url_video', models.URLField()),
                ('nameCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_course', to='courses.Course', verbose_name='Курс')),
            ],
        ),
    ]
