# Generated by Django 2.1.7 on 2019-05-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_url_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessoncourse',
            options={'ordering': ['nameDay']},
        ),
    ]
