# Generated by Django 2.1.7 on 2019-03-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20190318_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='course',
        ),
    ]
